# Generated by Django 5.0 on 2024-01-09 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_category_postcategory_categorytrough_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='commentPost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commentUser',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_time',
            new_name='dateCreation',
        ),
    ]
