# Generated by Django 5.0 on 2024-01-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_post_comment_commentpost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dateCreation',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentPost',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentUser',
            new_name='user',
        ),
    ]
